language: python
cache: pip
dist: xenial

matrix:
  include:
    - python: 3.6
      env: GROUP=js SUBGROUP=lint
    - python: 3.5
      env: GROUP=python TOXENV=py35
    - python: 3.6
      env: GROUP=python TOXENV=py36
    - python: 3.7
      env: GROUP=python TOXENV=py37

install:
  - "if [[ \"$GROUP\" == python ]] ; then pip install tox ; fi"
  - "if [[ \"$GROUP\" == js ]] ; then npm install ; fi"

script:
  - "if [[ \"$GROUP\" == python ]] ; then tox ; fi"
  - "if [[ \"$GROUP\" == js ]] && [[ \"$SUBGROUP\" == lint ]] ; then npm run prettier:check ; fi"
